Repository FuelLabs/sway-applications, pull requests merged in 2022-07, with the labels that each got.

#125 Bumped fundraiser and multisig to v0.17
  fundraiser/src/contract_abi.sw
  fundraiser/src/main.sw
  multisig-wallet/src/contract_abi.sw
  multisig-wallet/src/main.sw
Labels: Good First Issue, Repo Misc

#79 feat: dao sc
  .github/scripts/build.sh
  .github/workflows/ci.yml
  README.md
  dao-voting/.docs/dao-voting-logo.png
  dao-voting/.gitignore
  dao-voting/Cargo.toml
  dao-voting/Forc.toml
  dao-voting/README.md
  dao-voting/src/dao_voting_abi.sw
  dao-voting/src/data_structures.sw
  dao-voting/src/errors.sw
  dao-voting/src/events.sw
  dao-voting/src/main.sw
  dao-voting/src/utils.sw
  dao-voting/tests/artifacts/gov_token/.gitignore
  dao-voting/tests/artifacts/gov_token/Cargo.toml
  dao-voting/tests/artifacts/gov_token/Forc.toml
  dao-voting/tests/artifacts/gov_token/src/main.sw
  dao-voting/tests/harness.rs
  dao-voting/tests/utils/mod.rs
Labels: New Feature, App: DAO

#136 Change app images from transparent to a white background
  .docs/logo.png
  dao-voting/.docs/dao-logo.png
  dao-voting/.docs/dao-voting-logo.png
  dao-voting/README.md
  fundraiser/.docs/fundraiser-logo.png
  multisig-wallet/.docs/multi-signature-logo.png
Labels: Good First Issue, Improvement, Repo Misc

#144 chore: update logo to work on dark and light theme
  .docs/logo.png
  .docs/sway-apps-logo-dark-theme.png
  .docs/sway-apps-logo-light-theme.png
  README.md
Labels: Documentation

#143 chore: use `concurrency` to cancel previous CI runs
  .github/workflows/ci.yml
Labels: Repo Misc

#156 Bumped apps to forc v0.18
  dao-voting/src/main.sw
  escrow/src/main.sw
  fundraiser/src/main.sw
  multisig-wallet/src/main.sw
Labels: Good First Issue, Repo Misc

#155 Update logo in each app to work automatically based on light/dark theme
  dao-voting/.docs/dao-logo-dark-theme.png
  dao-voting/.docs/dao-logo-light-theme.png
  dao-voting/.docs/dao-logo.png
  dao-voting/README.md
  fundraiser/.docs/fundraiser-logo-dark-theme.png
  fundraiser/.docs/fundraiser-logo-light-theme.png
  fundraiser/.docs/fundraiser-logo.png
  fundraiser/README.md
  multisig-wallet/.docs/multi-signature-logo-dark-theme.png
  multisig-wallet/.docs/multi-signature-logo-light-theme.png
  multisig-wallet/.docs/multi-signature-logo.png
  multisig-wallet/README.md
Labels: Documentation, Good First Issue, Repo Misc

#174 refactor: move function comments to abi
  dao-voting/src/dao_voting_abi.sw
  dao-voting/src/interface.sw
  dao-voting/src/main.sw
Labels: Improvement, App: DAO

#176 Bumping to v0.19.0
  dao-voting/src/main.sw
  dao-voting/src/utils.sw
  escrow/src/main.sw
  fundraiser/src/main.sw
  fundraiser/src/utils.sw
  multisig-wallet/src/main.sw
Labels: Repo Misc

#178 changed logo alt text
  fundraiser/README.md
Labels: Documentation, Good First Issue

#54 Upgrade the Escrow to be feature rich
  escrow/.docs/escrow-logo-dark-theme.png
  escrow/.docs/escrow-logo-light-theme.png
  escrow/.docs/escrow-sequence-diagram.png
  escrow/Cargo.toml
  escrow/README.md
  escrow/SPECIFICATION.md
  escrow/src/data_structures.sw
  escrow/src/errors.sw
  escrow/src/events.sw
  escrow/src/interface.sw
  escrow/src/main.sw
  escrow/tests/harness.rs
  escrow/tests/utils/mod.rs
Labels: Improvement, App: Escrow
