Repository FuelLabs/sway-applications, pull requests merged in 2022-09, with the labels that each got.

#213 Update command used to build the dao project
  dao-voting/README.md
Labels: Documentation, App: DAO

#208 New document to track the progress of each app
  APPLICATION_PROGRESS.md
  README.md
Labels: Documentation

#214 Rewrite the `fundraiser` spec to be closer to the spec for the `escrow`
  APPLICATION_PROGRESS.md
  fundraiser/.docs/fundraiser-sequence-diagram.png
  fundraiser/README.md
  fundraiser/SPECIFICATION.md
  fundraiser/src/main.sw
Labels: Documentation, Good First Issue, App: Fundraiser

#198 Mattauer/oracle sc
  .github/scripts/build.sh
  .github/workflows/ci.yml
  APPLICATION_PROGRESS.md
  README.md
  oracle/.docs/oracle-logo-dark-theme.png
  oracle/.docs/oracle-logo-light-theme.png
  oracle/.docs/oracle_diagram.png
  oracle/.gitignore
  oracle/Cargo.toml
  oracle/Forc.toml
  oracle/README.md
  oracle/SPECIFICATION.md
  oracle/src/data_structures.sw
  oracle/src/errors.sw
  oracle/src/events.sw
  oracle/src/interface.sw
  oracle/src/main.sw
  oracle/tests/functions/mod.rs
  oracle/tests/functions/owner.rs
  oracle/tests/functions/price.rs
  oracle/tests/functions/set_price.rs
  oracle/tests/harness.rs
  oracle/tests/utils/mod.rs
Labels: New Feature, App: Oracle

#216 fix: broken installation link
  README.md
Labels: Documentation, Good First Issue

#217 fix: change order of parameters
  escrow/tests/functions/accept_arbiter.rs
  escrow/tests/functions/create_escrow.rs
  escrow/tests/functions/deposit.rs
  escrow/tests/functions/dispute.rs
  escrow/tests/functions/propose_arbiter.rs
  escrow/tests/functions/resolve_dispute.rs
  escrow/tests/functions/return_deposit.rs
  escrow/tests/functions/take_payment.rs
  escrow/tests/functions/transfer_to_seller.rs
  escrow/tests/functions/withdraw_collateral.rs
  escrow/tests/utils/mod.rs
Labels: Good First Issue, Improvement, App: Escrow

#160 Airdrop Smart Contract
  .github/scripts/build.sh
  .github/workflows/ci.yml
  APPLICATION_PROGRESS.md
  README.md
  airdrop/.docs/airdrop-distributor_dark.png
  airdrop/.docs/airdrop-distributor_light.png
  airdrop/.docs/airdrop-sequence-diagram.png
  airdrop/README.md
  airdrop/SPECIFICATION.md
  airdrop/airdrop-distributor/.gitignore
  airdrop/airdrop-distributor/Cargo.toml
  airdrop/airdrop-distributor/Forc.toml
  airdrop/airdrop-distributor/src/data_structures.sw
  airdrop/airdrop-distributor/src/errors.sw
  airdrop/airdrop-distributor/src/events.sw
  airdrop/airdrop-distributor/src/interface.sw
  airdrop/airdrop-distributor/src/main.sw
  airdrop/airdrop-distributor/src/utils.sw
  airdrop/airdrop-distributor/tests/functions/claim.rs
  airdrop/airdrop-distributor/tests/functions/claim_data.rs
  airdrop/airdrop-distributor/tests/functions/constructor.rs
  airdrop/airdrop-distributor/tests/functions/end_block.rs
  airdrop/airdrop-distributor/tests/functions/merkle_root.rs
  airdrop/airdrop-distributor/tests/functions/mod.rs
  airdrop/airdrop-distributor/tests/harness.rs
  airdrop/airdrop-distributor/tests/utils/mod.rs
  airdrop/simple-asset/.gitignore
  airdrop/simple-asset/Cargo.toml
  airdrop/simple-asset/Forc.toml
  airdrop/simple-asset/src/errors.sw
  airdrop/simple-asset/src/interface.sw
  airdrop/simple-asset/src/main.sw
  airdrop/simple-asset/tests/functions/constructor.rs
  airdrop/simple-asset/tests/functions/mint_to.rs
  airdrop/simple-asset/tests/functions/mod.rs
  airdrop/simple-asset/tests/harness.rs
  airdrop/simple-asset/tests/utils/mod.rs
Labels: New Feature, App: Airdrop

#222 Standardize Tests Across Repo
  NFT/tests/functions/admin.rs
  NFT/tests/functions/approve.rs
  NFT/tests/functions/burn.rs
  NFT/tests/functions/constructor.rs
  NFT/tests/functions/meta_data.rs
  NFT/tests/functions/mint.rs
  NFT/tests/functions/set_admin.rs
  NFT/tests/functions/transfer_from.rs
  dao-voting/tests/functions/constructor.rs
  dao-voting/tests/functions/create_proposal.rs
  dao-voting/tests/functions/deposit.rs
  dao-voting/tests/functions/execute.rs
  dao-voting/tests/functions/governance_token_id.rs
  dao-voting/tests/functions/proposal.rs
  dao-voting/tests/functions/unlock_votes.rs
  dao-voting/tests/functions/user_votes.rs
  dao-voting/tests/functions/vote.rs
  dao-voting/tests/functions/withdraw.rs
  escrow/tests/functions/accept_arbiter.rs
  escrow/tests/functions/create_escrow.rs
  escrow/tests/functions/deposit.rs
  escrow/tests/functions/dispute.rs
  escrow/tests/functions/propose_arbiter.rs
  escrow/tests/functions/resolve_dispute.rs
  escrow/tests/functions/return_deposit.rs
  escrow/tests/functions/take_payment.rs
  escrow/tests/functions/transfer_to_seller.rs
  escrow/tests/functions/withdraw_collateral.rs
  fundraiser/tests/functions/pledge.rs
  oracle/tests/functions/set_price.rs
Labels: Good First Issue, Improvement, Repo Misc

#226 Bumping CI to use `forc v0.24.4`
  .github/workflows/ci.yml
  NFT/src/main.sw
  airdrop/airdrop-distributor/src/interface.sw
  airdrop/airdrop-distributor/src/main.sw
  dao-voting/src/interface.sw
  escrow/src/interface.sw
  escrow/src/main.sw
  fundraiser/src/data_structures.sw
  fundraiser/src/interface.sw
  multisig-wallet/src/contract_abi.sw
Labels: Repo Misc

#227 add forc and fuel-core version specification to README.md
  README.md
Labels: Documentation, Good First Issue

#237 Add a branch at the end of the build.sh script to crash if the project does not match the conditions above
  .github/scripts/build.sh
Labels: Good First Issue, Improvement

#218 Convert CONTRIBUTING.md into a Sway Application Book
  .docs/contributing-book/.gitignore
  .docs/contributing-book/README.md
  .docs/contributing-book/book.toml
  .docs/contributing-book/src/SUMMARY.md
  .docs/contributing-book/src/code/bad_documentation/.gitignore
  .docs/contributing-book/src/code/bad_documentation/Cargo.toml
  .docs/contributing-book/src/code/bad_documentation/Forc.toml
  .docs/contributing-book/src/code/bad_documentation/src/lib.sw
  .docs/contributing-book/src/code/bad_documentation/tests/harness.rs
  .docs/contributing-book/src/code/connect_four/.gitignore
  .docs/contributing-book/src/code/connect_four/Cargo.toml
  .docs/contributing-book/src/code/connect_four/Forc.toml
  .docs/contributing-book/src/code/connect_four/src/data_structures.sw
  .docs/contributing-book/src/code/connect_four/src/errors.sw
  .docs/contributing-book/src/code/connect_four/src/events.sw
  .docs/contributing-book/src/code/connect_four/src/interface.sw
  .docs/contributing-book/src/code/connect_four/src/main.sw
  .docs/contributing-book/src/code/connect_four/src/utils.sw
  .docs/contributing-book/src/code/connect_four/tests/harness.rs
  .docs/contributing-book/src/code/style_guide/.gitignore
  .docs/contributing-book/src/code/style_guide/Cargo.toml
  .docs/contributing-book/src/code/style_guide/Forc.toml
  .docs/contributing-book/src/code/style_guide/src/lib.sw
  .docs/contributing-book/src/code/style_guide/tests/harness.rs
  .docs/contributing-book/src/documentation/issues/create-issue.md
  .docs/contributing-book/src/documentation/issues/index.md
  .docs/contributing-book/src/documentation/issues/search/assignment.md
  .docs/contributing-book/src/documentation/issues/search/filtering.md
  .docs/contributing-book/src/documentation/issues/search/index.md
  .docs/contributing-book/src/documentation/issues/search/summary.md
  .docs/contributing-book/src/documentation/project-quality/code-structure.md
  .docs/contributing-book/src/documentation/project-quality/documentation/code/abi.md
  .docs/contributing-book/src/documentation/project-quality/documentation/code/comments.md
  .docs/contributing-book/src/documentation/project-quality/documentation/code/index.md
  .docs/contributing-book/src/documentation/project-quality/documentation/code/naming-components.md
  .docs/contributing-book/src/documentation/project-quality/documentation/code/style.md
  .docs/contributing-book/src/documentation/project-quality/documentation/index.md
  .docs/contributing-book/src/documentation/project-quality/documentation/read-me.md
  .docs/contributing-book/src/documentation/project-quality/documentation/specification.md
  .docs/contributing-book/src/documentation/project-quality/index.md
  .docs/contributing-book/src/documentation/project-quality/project-structure.md
  .docs/contributing-book/src/documentation/project-quality/testing.md
  .docs/contributing-book/src/documentation/pull-requests/commit.md
  .docs/contributing-book/src/documentation/pull-requests/creating-pr.md
  .docs/contributing-book/src/documentation/pull-requests/index.md
  .docs/contributing-book/src/documentation/welcome.md
  .docs/contributing-book/src/images/app-documentation.png
  .docs/contributing-book/src/images/app-filter-assignee.png
  .docs/contributing-book/src/images/app-filter-comments.png
  .docs/contributing-book/src/images/app-filter.png
  .docs/contributing-book/src/images/filter-dropdown.png
  .docs/contributing-book/src/images/issue-templates.png
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  CONTRIBUTING.md
Labels: Documentation, Repo Misc

#239 Updating paths and command to build book
  .github/workflows/gh-pages.yml
Labels: Bug, Repo Misc

#241 Removed github pages redirect content
  .github/workflows/gh-pages.yml
Labels: Repo Misc

#242 Updated contributing references
  NFT/README.md
  README.md
  airdrop/README.md
  dao-voting/README.md
  escrow/README.md
  fundraiser/README.md
  multisig-wallet/README.md
  oracle/README.md
Labels: Documentation, Repo Misc

#243 Add a link to the repository for the new book
  .docs/contributing-book/book.toml
Labels: Documentation, Repo Misc

#245 Application book has a `run` feature that should be disabled in code snippets
  .docs/contributing-book/book.toml
  .docs/contributing-book/src/documentation/project-quality/documentation/code/abi.md
  .docs/contributing-book/src/documentation/project-quality/documentation/code/comments.md
  .docs/contributing-book/src/documentation/project-quality/documentation/code/style.md
  .docs/contributing-book/src/documentation/project-quality/project-structure.md
  .docs/contributing-book/theme/highlight.js
Labels: Bug, Documentation
