Repository FuelLabs/sway-applications, pull requests merged in 2022-06, with the labels that each got.

#56 Moved scripts into .github/scripts
  .github/scripts/build.sh
  .github/scripts/forc_badge_check.sh
  .github/workflows/ci.yml
  forc_badge_check.sh
Labels: Good First Issue, Improvement

#49 Update issue templates
  .github/ISSUE_TEMPLATE/brand_new_feature.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/improvement_to_existing_feature.yml
  .github/ISSUE_TEMPLATE/new_application.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation, New Feature, Good First Issue

#58 Moving logo to hidden dir and updating readme path
  .docs/logo.png
  README.md
Labels: Documentation, Good First Issue

#63 Added self to CODEOWNERS
  .github/CODEOWNERS
Labels: New Feature

#84 Merged sections into 1 motivation
  .github/ISSUE_TEMPLATE/brand_new_feature.yml
  .github/ISSUE_TEMPLATE/improvement_to_existing_feature.yml
  .github/ISSUE_TEMPLATE/new_application.yml
Labels: Improvement

#87 Bumped Escrow to 0.15.2
  .github/workflows/ci.yml
  escrow/Cargo.toml
  escrow/src/main.sw
  escrow/tests/artifacts/asset/Cargo.toml
Labels: Improvement

#89 Update README.md in root to point at latest forc via the badge
  .github/scripts/forc_badge_check.sh
  .github/workflows/ci.yml
  README.md
Labels: Improvement

#41 Added transfer of assets to outputs & contracts
  .github/workflows/ci.yml
  multisig-wallet/.docs/multi-signature-logo.png
  multisig-wallet/README.md
  multisig-wallet/src/abi.sw
  multisig-wallet/src/data_structures.sw
  multisig-wallet/src/errors.sw
  multisig-wallet/src/events.sw
  multisig-wallet/src/main.sw
  multisig-wallet/tests/harness.rs
Labels: New Feature, Good First Issue

#86 Replaced compilation of forc and forc-fmt with binary fetch
  .github/workflows/ci.yml
Labels: Improvement

#94 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#90 Multisig supports 25 users / signatures via hardcoded array limit
  README.md
  multisig-wallet/src/abi.sw
  multisig-wallet/src/data_structures.sw
  multisig-wallet/src/events.sw
  multisig-wallet/src/main.sw
Labels: Improvement

#100 Bumping `Escrow` & `Multisig` to `v16.0.1`
  escrow/src/main.sw
  multisig-wallet/src/abi.sw
  multisig-wallet/src/main.sw
Labels: Good First Issue, Improvement

#103 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement

#67 Fundraiser program
  .github/scripts/build.sh
  .github/workflows/ci.yml
  README.md
  fundraiser/.docs/fundraiser-logo.png
  fundraiser/.gitignore
  fundraiser/Cargo.toml
  fundraiser/Forc.toml
  fundraiser/README.md
  fundraiser/SPECIFICATION.md
  fundraiser/src/abi.sw
  fundraiser/src/data_structures.sw
  fundraiser/src/errors.sw
  fundraiser/src/events.sw
  fundraiser/src/main.sw
  fundraiser/src/utils.sw
  fundraiser/tests/artifacts/asset/.gitignore
  fundraiser/tests/artifacts/asset/Cargo.toml
  fundraiser/tests/artifacts/asset/Forc.toml
  fundraiser/tests/artifacts/asset/src/main.sw
  fundraiser/tests/harness.rs
  fundraiser/tests/utils/mod.rs
Labels: New Feature, App: Fundraiser

#117 Update issue templates to suggest a h4 heading instead of h1
  .github/ISSUE_TEMPLATE/brand_new_feature.yml
  .github/ISSUE_TEMPLATE/improvement_to_existing_feature.yml
  .github/ISSUE_TEMPLATE/new_application.yml
Labels: Good First Issue, Improvement, Repo Misc
