Repository FuelLabs/sway-applications, pull requests merged in 2024-03, with the labels that each got.

#776 Improvement :fix 11 issues
  DAO/project/contracts/DAO-contract/src/interface.sw
  auctions/english-auction/project/contracts/auction-contract/src/events.sw
  auctions/english-auction/project/contracts/auction-contract/src/interface.sw
  fundraiser/project/contracts/fundraiser-contract/src/data_structures/campaign_state.sw
  fundraiser/project/contracts/fundraiser-contract/src/interface.sw
  native-assets/NFT/project/contracts/NFT-contract/src/main.sw
  native-assets/fractional-NFT/project/contracts/test-artifacts/src/main.sw
  native-assets/native-asset/project/contracts/native-asset-contract/src/main.sw
  timelock/project/contracts/timelock-contract/src/events.sw
Labels: Documentation, Repo Misc

#778 Reduce Read/writes and add `get_board()` for TicTacToe
  games/TicTacToe/project/SPECIFICATION.md
  games/TicTacToe/project/contracts/tictactoe-contract/src/interface.sw
  games/TicTacToe/project/contracts/tictactoe-contract/src/main.sw
Labels: New Feature, Improvement, App: Games

#782 style: ui improvements
  README.md
  index.html
  public/fuel-logo-64.png
  scripts/build-website/utils.mjs
Labels: User Interface
